//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phimvietnamxua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phim
    {
        public int id { get; set; }
        public string maphim { get; set; }
        public string tenphim { get; set; }
        public string motaND { get; set; }
        public string chitietND { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string hashtag { get; set; }
        public string mainImage { get; set; }
        public string quocgia { get; set; }
        public string namSX { get; set; }
        public Nullable<int> chitietID { get; set; }
    
        public virtual chitietphim chitietphim { get; set; }
    }
}
